{% set name = "cosolvkit" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cosolvkit-{{ version }}.tar.gz
  sha256: 3a2b9609ad9fcf1f97578d5d9d17927ae5404f97aac56507016dc065dc29081c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - create_cosolvent_system=cosolvkit.cli.create_cosolvent_system:main
    - post_simulation_processing=cosolvkit.cli.post_simulation_processing:main

requirements:
  host:
    - python >=3.9
    - setuptools >=61.0
    - pip
  run:
    - python >=3.9
    - openmmforcefields >=0.12
    - pdbfixer
    - mdanalysis
    - espaloma
    - pymol-open-source
    - griddataformats

test:
  imports:
    - openmm
    - espaloma
    - cosolvkit  
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/forlilab/cosolvkit
  summary: CosolvKit
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: 'CosolvKit is a tool for cosolvent MD preparation and analysis'
  description: |
    CosolvKit is a tool for cosolvent MD preparation and analysis.
    It allows the user to parametrize any kind of cosolvent required
    defined by SMILES string at any concentration (M) or number of copies.
    It is built on top of OpenMM, hence it accepts all the forcefields
    available in OpenMM and it generates topology and coordinate files of the
    compatible with the required MD engine (OpenMM, Amber, GROMACS, CHARMM).
    MD simulations can be run either within cosolvkit or externally and CosolvKit
    provides a minimal analysis pipeline to analyse cosolvent densities from the trajectories.

extra:
  recipe-maintainers:
    - nbruciaferri
